services:
  app:
    build: .
    env_file: .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17.4
    env_file: .env
    expose:
      - ${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
